### ISSUE TITLE
CI coverage job failing: cargo llvm-cov not installed

### ISSUE THREAD

**Issue by lalitb** [open-telemetry/opentelemetry-rust-contrib#331]
Generated by copilot:

## Description: The CI workflow's coverage job is failing because the cargo llvm-cov command is not found. The error message is:

```
error: no such command: `llvm-cov`
help: view all installed commands with `cargo --list`
help: find a package to install `llvm-cov` with `cargo search cargo-llvm-cov`
```

## Failure context:
See the run: https://github.com/open-telemetry/opentelemetry-rust-contrib/actions/runs/15925461183/job/44921593056?pr=327 (ref: 570d4e7ea71c710cbfa590a19de097fc27ed39a5)

## Proposed solution: 
Update the coverage job in [.github/workflows/ci.yml (ref)](https://github.com/open-telemetry/opentelemetry-rust-contrib/blob/570d4e7ea71c710cbfa590a19de097fc27ed39a5/.github/workflows/ci.yml) to specify the tool in the install step, like so:

```YAML
- name: cargo install cargo-llvm-cov
  uses: taiki-e/install-action@2cab843126c0d8cf950bf55f4e9b8413f70f553f # v2.54.1
  with:
    tool: cargo-llvm-cov
```
This will ensure cargo-llvm-cov is installed before it's used.
